export {
  APP_COLORS as AUTO_VEHICLE_DETAIL_COLORS,
  APP_BUBBLE_SHELL as AUTO_VEHICLE_DETAIL_BUBBLE_SHELL,
  APP_STAT_AMOUNT_NEUTRAL as AUTO_VEHICLE_STAT_AMOUNT_NEUTRAL,
  APP_STAT_AMOUNT_POSITIVE as AUTO_VEHICLE_STAT_AMOUNT_POSITIVE,
  APP_STAT_AMOUNT_DANGER as AUTO_VEHICLE_STAT_AMOUNT_DANGER,
  APP_STAT_AMOUNT_SM_POSITIVE as AUTO_VEHICLE_STAT_AMOUNT_SM_POSITIVE,
} from "@/lib/app-theme";
