import {
  addMonthsToIsoDate,
  resolveLoanFirstPaymentDate,
} from "../loan";
import type { AutoVehicle } from "../vehicle";
import { readAutoVehicleRecords, writeAutoVehicleRecords } from "./storage";
import type { AutoVehicleRecord } from "./types";

function isPastOrToday(isoDate: string, asOf: Date) {
  const date = new Date(`${isoDate}T12:00:00.000Z`);
  const today = new Date(`${asOf.toISOString().slice(0, 10)}T12:00:00.000Z`);
  return date.getTime() <= today.getTime();
}

/** Прошедшие ежемесячные платежи по графику кредита */
export function buildAutoLoanPaymentRecords(
  vehicle: AutoVehicle,
  asOf: Date = new Date()
): Omit<AutoVehicleRecord, "id">[] {
  if (vehicle.financingType === "cash" || vehicle.status === "sold") {
    return [];
  }

  const loanTermMonths = vehicle.loanTermMonths ?? 0;
  const loanPayment = Math.max(0, vehicle.loanPayment ?? 0);

  if (loanPayment <= 0 || loanTermMonths <= 0) {
    return [];
  }

  const paymentStartDate = resolveLoanFirstPaymentDate(vehicle);
  const records: Omit<AutoVehicleRecord, "id">[] = [];

  for (let monthIndex = 0; monthIndex < loanTermMonths; monthIndex += 1) {
    const occurredOn = addMonthsToIsoDate(paymentStartDate, monthIndex);

    if (!isPastOrToday(occurredOn, asOf)) {
      break;
    }

    records.push({
      vehicleId: vehicle.id,
      kind: "payment",
      paymentType: "loan",
      amount: loanPayment,
      description: "Ежемесячный платёж",
      occurredAt: `${occurredOn}T12:00:00.000Z`,
      autoGenerated: true,
    });
  }

  return records;
}

function autoLoanRecordsMatch(
  vehicle: AutoVehicle,
  records: AutoVehicleRecord[],
  asOf: Date
) {
  const expected = buildAutoLoanPaymentRecords(vehicle, asOf);
  const actual = records
    .filter(
      (record) =>
        record.vehicleId === vehicle.id &&
        record.kind === "payment" &&
        record.autoGenerated &&
        record.paymentType === "loan"
    )
    .sort(
      (left, right) =>
        new Date(left.occurredAt).getTime() - new Date(right.occurredAt).getTime()
    );

  if (expected.length !== actual.length) {
    return false;
  }

  return expected.every((record, index) => {
    const current = actual[index];
    return (
      current.amount === record.amount &&
      current.occurredAt.slice(0, 10) === record.occurredAt.slice(0, 10)
    );
  });
}

/** Обновить автоплатежи: ручные записи сохраняются, сгенерированные — пересчитываются */
export function syncAutoVehicleLoanPayments(vehicle: AutoVehicle, asOf: Date = new Date()) {
  const existing = readAutoVehicleRecords();

  if (autoLoanRecordsMatch(vehicle, existing, asOf)) {
    return;
  }

  const preserved = existing.filter(
    (record) =>
      record.vehicleId !== vehicle.id ||
      record.kind !== "payment" ||
      !record.autoGenerated
  );
  const generated = buildAutoLoanPaymentRecords(vehicle, asOf).map((record) => ({
    ...record,
    id: crypto.randomUUID(),
  }));
  writeAutoVehicleRecords([...generated, ...preserved]);

  if (typeof window !== "undefined") {
    window.dispatchEvent(new Event("dengi:auto-vehicle-records-updated"));
  }
}
