export type AutoVehicleRecordKind = "payment" | "expense";

export type AutoVehiclePaymentType = "loan" | "extra" | "insurance";

export type AutoVehicleExpenseType =
  | "fuel"
  | "service"
  | "upgrade"
  | "insurance"
  | "parking"
  | "other";

export type AutoVehicleRecord = {
  id: string;
  vehicleId: string;
  kind: AutoVehicleRecordKind;
  amount: number;
  description: string;
  occurredAt: string;
  autoGenerated?: boolean;
  paymentType?: AutoVehiclePaymentType;
  expenseType?: AutoVehicleExpenseType;
  /** Пользовательская категория — из «Другое» */
  customExpenseCategoryId?: string;
};
